```{r}
library(microbenchmark)
vroom_mat <- function(path) {
  combined <- vroom::vroom(path)
  combined %<>% mutate(state = factor(state, levels = state_order),
                     region = factor(region, levels = region_order))
}

readr_mut <- function(path) {
  combined <- readr::read_tsv("/Users/rf/newselect201905/sq_gen/sq_gen/squirrelBox/combined.tsv", progress = F)
  combined %<>% mutate(state = factor(state, levels = state_order),
                     region = factor(region, levels = region_order))
}
benchmark <- microbenchmark(vroom = vroom::vroom("/Users/rf/newselect201905/sq_gen/sq_gen/squirrelBox/combined.tsv"), 
                            vroom_mat = vroom_mat("/Users/rf/newselect201905/sq_gen/sq_gen/squirrelBox/combined.tsv"), 
               read_tsv = readr_mut("/Users/rf/newselect201905/sq_gen/sq_gen/squirrelBox/combined.tsv"),
               #read_gz = readr::read_tsv("/Users/rf/newselect201905/sq_gen/sq_gen/squirrelBox/combined.tsv.gz", progress = F), 
               times = 2)
print(benchmark, signif = 2)


benchmark <- microbenchmark(
  read_tsv_guess = readr::read_csv("/Users/rf/newselect201905/sq_gen/sq_gen/squirrelBox/combined2.csv", col_types = cols()),
  read_tsv_string = readr::read_csv("/Users/rf/newselect201905/sq_gen/sq_gen/squirrelBox/combined2.csv", col_types = "ccncc"),
  fread = data.table::fread("/Users/rf/newselect201905/sq_gen/sq_gen/squirrelBox/combined2.csv",  nThread = 4),
  times = 2)

benchmark2 <- microbenchmark(
  read_tsv_guess = readr::read_csv("/Users/rf/newselect201905/sq_gen/sq_gen/squirrelBox/combined3.csv", col_types = cols()),
  read_tsv_string = readr::read_csv("/Users/rf/newselect201905/sq_gen/sq_gen/squirrelBox/combined3.csv"),
  fread = data.table::fread("/Users/rf/newselect201905/sq_gen/sq_gen/squirrelBox/combined3.csv"),
  times = 2)
```

```{r}
library(microbenchmark)
saveRDS(temp2, "temp_mex3c.rds")
t3 <- readRDS("temp_mex3c.rds")
saveRDS(temp2, "temp_zfp36l2.rds")
t2 <- readRDS("temp_zfp36l2.rds")
benchmark2 <- microbenchmark(
  find_for2 = groups_to_letters(t2),
  find_graph2 = groups_to_letters_igraph(t2),
  find_for3 = groups_to_letters(t3),
  find_graph3 = groups_to_letters_igraph(t3),
  times = 100)
benchmark2
```


```{r}
library(profvis)
p <- profvis(shiny::runApp())
```


